	<section id="aviso_privacidad">
		<h1 class="stAv">AVISO DE PRIVACIDAD</h1>
		<h2 class="apriv">www.plazadelatecnologia.com</h2><br>
		<h2 class="apriv">Estimado Usuario:</h2>
<p class="apriv">En cumplimiento con la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y con el fin de Asegurar la protección y privacidad de los datos personales, así como regular el acceso, rectificación, cancelación, y oposición del manejo de los mismos Pasaje de Electrónica el Salvador, S.A. de C.V. (en adelante Plaza de la Tecnología) (a través de su página web www.plazadelatecnologia.com)  establece lo siguiente:<br>
	Plaza de la Tecnología, es el responsable de recabar sus datos personales a través de su página web, señalando como domicilio el ubicado en Bosque de Duraznos 61-6C, Colonia Bosques de las Lomas, Delegación Miguel Hidalgo, México Distrito Federal. C.P. 11700. Nuestros datos de contacto se encuentran en nuestra página de internet <br>
	www.plaza de la tecnología.com.
</p>
<br />  
<h2 class="apriv">1. Descripción del Aviso</h2>
<p class="apriv">Los términos que se utilizan en el presente aviso de privacidad (en lo sucesivo referido como “Aviso”) tendrán la definición que a los mismos le asigna la Ley Federal de  Protección de Datos Personales en posesión de los Particulares, publicada en el Diario Oficial de la Federación el 5 de julio de 2010(en lo sucesivo referida como la “Ley”). En su art. 3 Fracc. I<br />
Este Aviso específica el tipo de datos que Plaza de la Tecnología .recolecta a través de su pagina web, los fines para los cuales lleva a cabo el tratamiento de los mismos, así como los derechos con que cuenta el Usuario   al respecto. </p>
<br />  
<h2 class="apriv">2. Datos personales que recaba Plaza de la Tecnología a través de su página web</h2>
<p class="apriv">Los datos personales que puede recabar Plaza de la Tecnología de sus Usuarios  incluyen (i) nombres, apellidos, nacionalidad, ocupación, domicilios, teléfonos, correos electrónicos, claves del Registro Federal de Contribuyentes, clave Única de Registro de población; (ii) toda aquella información que el Usuario  ha proporcionado y/o le proporcione en virtud del uso de su página de internet ; (iii)  aquellos datos propios y relacionados con los servicios que presta a través de su sitio web ; (iv) y cualesquiera otros datos que se recaben de tiempo en tiempo con motivo de la prestación de los servicios.<br>
Toda información personal que identifica al Usuario , revelada de manera directa o por cualquier otro medio de contacto, podrá ser recopilada y tratada por Plaza de la Tecnología.<br>
Si el usuario utiliza los servicios del Sitio Web www.plazadelatecnologia.com y proporciona sus datos personales, significa que ha leído, entendido, acordado los términos expuestos en el presente Aviso de Privacidad y reconoce que:<br>
a)	El sitio web www.plazadelatecnologia.com . puede incluir enlaces a sitios web de terceros, que de accederse, ocasionara que se abandone el sitio web www.plazadelatecnologia.com  por lo cual Plaza de la Tecnología  no asume ninguna responsabilidad en relación con esos sitios web de terceros.<br>
b)	El sitio web www.plazadelateconologia.com puede incluir enlaces que administren redes sociales, en cuyo caso el Usuario acepta que al proporcionar cualquier tipo de información o datos en dichos sitios, ocasionara que la misma pueda ser leída, vista, accedida, retransmitida y tratada por cualquier persona, y por lo tanto libera de cualquier responsabilidad a Plaza de la Tecnología.<br>
c)	Es posible que los sistemas de la pagina web www.plazadelatecnologia.com  recopilen datos del Usuario  tales como tipo de navegador, sistema operativo, páginas de internet visitadas, dirección IP, etc., a través de “cookies” o “web beacons”, entre otros, con el fin de recabar información para reconocer al Usuario al momento de entrar a la página web de Plaza de la Tecnología y ofrecerle una experiencia personalizada.<br> 
d)	Al momento de contratar un servicio o comprar un producto en la página web de Plaza de la Tecnología, se direccionará al usuario a una página web distinta, donde bajo su responsabilidad y bajo los lineamientos de Protección de Datos de dicha pagina, el Usuario proporcionará sus datos<br>
La recolección de datos que realiza Plaza de la Tecnología es de buena fe y por tal motivo presume que los mismos son  verídicos, correctos, completos e identifican al Usuario  que los suministra y/o provee, por lo que es responsabilidad del Usuario  que los datos que este le proporcione a Plaza de la Tecnología través de su sitio web .cumplan con tales características y se actualicen en la medida que se requiera, por lo que en ningún momento Plaza de la Tecnología es responsable de la veracidad de los datos e información proporcionados por los Usuarios así como de los contenidos que los mismos viertan en la página web. De igual forma, Plaza de la Tecnología .se reserva el derecho de ejercer las acciones que considere pertinentes en caso de falsedad de datos.<br>
En el caso de los Datos sensibles que el Usuario  no ha proporcionado y en ningún caso proporcionara a Plaza de  la Tecnología  los datos personales sensibles, es decir, aquellos datos personales que afecten a la esfera mas intima de su titular, o cuya utilización indebida pueda dar origen a discriminación o conlleve un riesgo grave para este. En particular, se consideran sensibles aquellos que puedan revelar aspectos como origen racial o étnico, estado de salud presente y futuro, información genética, creencias, religiosas, filosóficas y morales, afiliación sindical, opiniones, políticas, preferencia sexual, o conlleve un riesgo grave para éste. En particular, el Subarrendatario se obliga a no proporcionar a Plaza de la Tecnología  ningún Dato relativo a origen racial o étnico, estado de salud presente y futuro, información genética, creencias religiosas, filosóficas y morales, afiliación sindical, opiniones políticas o preferencia sexual. Tal y como lo señala el art. 3 fracc. VI de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.<br> 
</p> 
<br />  
<h2 class="apriv">3. Finalidad con que se recaban los datos personales.</h2>
<p class="apriv">Los datos personales podrán ser tratados y utilizados por Plaza de la Tecnología  y/o subsidiarias y/o afiliadas y/o terceros, nacionales y extranjeros para llevar a cabo alguna o todas las actividades relacionadas con el cumplimiento de las obligaciones que deriven de la relación contractual y/o  comercial que se originen y/o deriven de la prestación de servicios a través de su página web, con el propósito de informar al Usuario  sobre cambios relacionados con el servicio contratado, proveer los productos y servicios que ha solicitado, notificarle de nuevos productos o servicios, elaborar estudios y programas que son necesarios para determinar hábitos de consumo, realizar evaluaciones periódicas de nuestros productos y servicios para mejorar su calidad, y en general, así como para cualquier otra actividad tendiente a promover, mantener, mejorar , evaluar y cumplir los servicios.</p>
<br />  
<h2 class="apriv">4. Transferencia de datos personales.</h2>
<p class="apriv">Plaza de la Tecnología  podrá transferir los datos personales que haya recibido y/o recolectado y/o llegue a recibir y/o recolectar de sus Usuarios a sus subsidiarias y/o afiliadas y/o terceros, ya sean nacionales y/o extranjeros, y/o cualquier autoridad competente que así lo solicite para llevar a cabo las finalidades descritas en el punto 3 del presente aviso; La transferencia de los datos personales del Usuario se encuentra limitada a aquellos actos, hechos y/o procedimientos que Plaza de la Tecnología requiera implementar a efecto de estar en posibilidad de cumplir con sus obligaciones, regulatorias y/o comerciales en el curso ordinario de sus operaciones. Si el Usuario  no manifiesta su oposición para que sus datos personales sean transferidos, se entenderá que ha otorgado su consentimiento para ello, tal y como lo señala el art. 8 de la Ley Federal de Protección de Datos Personales en Posesión de los Particulares.</p>
<br />  
<h2 class="apriv">5. Derechos ARCO (Acceso, Rectificación, Cancelación Y Oposición)</h2>
<p class="apriv">Como titular de datos personales, el "Usuario" podrá ejercitar los derechos ARCO (acceso, cancelación, rectificación y oposición al tratamiento de sus datos personales), o bien, revocar el consentimiento que haya otorgado a Plaza de la Tecnología, para el tratamiento de sus datos personales, enviando directamente su solicitud al correo electrónico: <a href="mailto:modificaciones@apeplazas.com">modificaciones@apeplazas.com</a><br>
Dicha solicitud deberá contener por lo menos: (i) nombre y domicilio u otro medio para comunicarle la respuesta a su solicitud; (ii) los documentos que acrediten su identidad o, en su caso, la representación legal; (iii) la descripción clara y precisa de los datos personales respecto de los que se solicita ejercer alguno de los derechos ARCO, (iv) la manifestación expresa para revocar su consentimiento al tratamiento de sus datos personales y por tanto, para que no se usen; (vi) cualquier otro elemento que facilite la localización de los datos personales.<br> 
Su petición deberá ir acompañada de los fundamentos por los que solicita dicha revocación y una identificación oficial del titular de los datos o de su apoderado. En un plazo máximo de 20 (veinte) días hábiles atenderemos su solicitud y le informaremos sobre la procedencia de la misma a través del correo electrónico del que provenga la petición.<br>   
Plaza de la Tecnología  solicita al usuario que actualice sus datos cada vez que éstos sufran alguna modificación, ya que esto permitirá brindarle un servicio eficiente y personalizado.</p>
<br />  
<h2 class="apriv">6. Modificaciones al aviso de privacidad</h2>
<p class="apriv">Plaza de la Tecnología expresamente se reserva el derecho, bajo su exclusiva discreción, de cambiar, modificar, agregar o eliminar partes del presente Aviso en cualquier momento de acuerdo a sus necesidades comerciales o requerimientos de ley. En tal caso, Plaza de la Tecnología  informara las modificaciones que se le practiquen al Aviso vía correo electrónico. En la medida que el Usuario no solicite, en los términos antes mencionados, la cancelación y/u oposición de sus datos personales, implicara que ha aceptado y consentido tales cambios y/o modificaciones.<br>
Al proporcionarle sus datos personales a Plaza de la Tecnología través de su página web el Usuario  expresamente reconoce y acepta el presente Aviso, según el mismo pueda ser modificado o ajustado, y otorga su consentimiento para que Plaza de la Tecnología  proceda con el procesamiento de sus datos personales de la forma que se explica en el presente Aviso. Si el Usuario  no acepta este Aviso podrá ejercer los derechos que le confiere la Ley.</p>
<br>
<h2 class="apriv">7. Limitación de uso y divulgación de información</h2>
<p class="apriv">En nuestro programa de notificación de promociones, ofertas y servicios a través de correo electrónico, sólo Plaza de la Tecnología tiene acceso a la información recabada. Este tipo de publicidad se realiza mediante avisos y mensajes promocionales de correo electrónico, los cuales sólo serán enviados a usted y a aquellos contactos registrados para tal propósito, esta indicación podrá usted modificarla en cualquier momento enviando un correo amodificaciones@apeplazas.com.En los correos electrónicos enviados, pueden incluirse ocasionalmente ofertas de terceras partes que sean nuestros socios comerciales.<br>
Sus datos personales serán tratados con base a en los principios de licitud, consentimiento, información, calidad, finalidad, lealtad, proporcionalidad y responsabilidad en términos de la Legislación.</p>
<br>
<h2 class="apriv">8. Protección</h2>
<p class="apriv">El "Usuario" puede reconocer fácilmente la utilización del sistema de seguridad en las zonas o página determinada para la compra de "Productos y Servicios" en el sitio www.plazadelatecnología.com cuando el navegador despliegue el icono de un pequeño candado en la parte inferior derecha de la pantalla o en la barra de navegación de su explorador de internet, en el cual se indica a petición del "Usuario" al hacer clic sobre él, que la navegación o consulta y transacciones se están llevando a cabo bajo un ambiente totalmente seguro.<br>
Asimismo se le informa al "Usuario", que todas las transacciones comerciales son realizadas en un entorno de servidor seguro bajo protocolo SSL y todas las comunicaciones se transmiten encriptadas, Plaza de la Tecnología cuentan con la plataforma "Geotrust premium" que asegura un alto nivel de protección a las comunicaciones dispuesto por Plaza de la Tecnología.<br>
También pueden optar por ser direccionado a las páginas Web de PayPal, Dineromail o MercadoPago (para realizar su pago) que también ofrecen seguridad y confidencialidad de los datos que proporciona, para ello, cuentan con un servidor seguro bajo el protocolo SSL (Secure Socket Layer).<br>
Sin embargo, y a pesar de contar cada día con herramientas más seguras, la protección de los datos enviados a través de Internet no se puede garantizar al 100%; por lo que una vez recibidos, se hará todo lo posible por salvaguardar la información.</p>
<br>
<h2 class="apriv">9. AUTORIDAD </h2>
<p class="apriv">Si el usuario considera que han sido vulnerados sus derechos respecto de la protección de datos personales, tiene el derecho de acudir a la autoridad correspondiente para defender su ejercicio. La autoridad es el Instituto Federal de Acceso a la Información y Protección de Datos (IFAI), su sitio web es: <a href="http://www.ifai.mx">www.ifai.mx</a>.<br>
Fecha de la última actualización.<br>
Estimado usuario, se le notifica que el Aviso de Privacidad ha sido modificado el día 13 de marzo de 2014.
</p>
<br>
</section>